version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i npm@latest -g
      - npm cache clean --force
      - rm -rf node_modules package-lock.json
      - npm install

  pre_build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://${DeployBucket}/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://${DeployBucket}/
      - aws cloudfront create-invalidation --distribution-id ${Distribution} --paths /index.html /service-worker.js
artifacts:
  files:
    - '**/*'
  base-directory: build